"""
Adaptive Intelligent Model Decision (AIMD) Engine Foundation for PhoenixML.

This module provides the analytical decision-support foundation for PhoenixML.
Given observed model health, performance trends, data drift, concept drift,
and explainability evidence, the AIMD Decision Engine evaluates deterministic
decision rules to generate actionable maintenance recommendations for human review.

CRITICAL ARCHITECTURAL CONSTRAINTS:
1. DECISION SUPPORT ONLY: PhoenixML is NOT an autonomous or self-healing platform.
   The engine generates recommendations for authorized human review and approval.
   `requires_human_approval` is strictly and unconditionally True on every recommendation.
2. NO AUTONOMOUS EXECUTION: The engine does not retrain, rollback, deploy, or modify models.
3. ROLLBACK SAFETY: The engine NEVER recommends ROLLBACK simply because health is critical
   or drift is detected. A ROLLBACK recommendation requires verified historical maintenance
   context confirming an available, viable rollback target model. If unavailable or missing,
   the engine falls back to RETRAIN or HUMAN_REVIEW.
4. DECOUPLED ANALYTICAL MODULE:
   - Pure domain logic, independent of FastAPI, Starlette, HTTP routers, and endpoints.
   - Independent of SQLAlchemy, database engines, sessions, and persistence models.
   - Independent of background workers, celery, MLflow, or external decision libraries.
"""

import math
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple
from pydantic import BaseModel, Field

from app.monitoring.concept_drift import ConceptDriftAnalysis, ConceptDriftStatus
from app.monitoring.data_drift import DataDriftAnalysis
from app.monitoring.health import HealthAssessmentResult, HealthStatus
from app.monitoring.performance import PerformanceAnalysis, PerformanceStatus
from app.monitoring.explainability import ExplanationResult


class AIMDAction(str, Enum):
    """
    Controlled set of maintenance actions recommended by the AIMD Engine.
    All actions require human review and approval before execution.
    """
    CONTINUE_MONITORING = "CONTINUE_MONITORING"
    INCREASED_MONITORING = "INCREASED_MONITORING"
    RETRAIN = "RETRAIN"
    ROLLBACK = "ROLLBACK"
    DATA_COLLECTION = "DATA_COLLECTION"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class AIMDPriority(str, Enum):
    """
    Urgency classification for maintenance recommendations.
    """
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class AIMDConfidence(str, Enum):
    """
    Confidence rating reflecting the breadth and corroboration of analytical evidence.
    """
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class AIMDContext(BaseModel):
    """
    Aggregated input context consumable by the AIMD Decision Engine.
    Contains outputs from upstream analytical stages and optional historical context.
    """
    health_assessment: Optional[HealthAssessmentResult] = None
    performance_analysis: Optional[PerformanceAnalysis] = None
    data_drift_analysis: Optional[DataDriftAnalysis] = None
    concept_drift_analysis: Optional[ConceptDriftAnalysis] = None
    explainability_result: Optional[ExplanationResult] = None
    prediction_confidence: Optional[float] = None
    historical_maintenance_context: Optional[Dict[str, Any]] = None


class AIMDRecommendation(BaseModel):
    """
    Structured recommendation generated by the AIMD Decision Engine.
    Consumable by UI presentation and human review workflows.
    """
    action: AIMDAction
    priority: AIMDPriority
    rationale: str
    supporting_signals: List[str] = Field(default_factory=list)
    health_score: Optional[float] = None
    health_status: Optional[str] = None
    confidence: AIMDConfidence
    requires_human_approval: bool = True
    evidence_summary: Dict[str, Any] = Field(default_factory=dict)


class AIMDConfiguration(BaseModel):
    """
    Configurable parameters and operational thresholds for AIMD decision logic.
    """
    critical_health_threshold: float = 60.0
    warning_health_threshold: float = 80.0
    data_drift_collection_threshold: int = 2


class AIMDDecisionEngine:
    """
    Deterministic rule-based decision engine for PhoenixML.
    Evaluates multi-source monitoring observations, drift reports, and explainability
    findings to recommend safe maintenance actions with human oversight.
    """

    def __init__(self, config: Optional[AIMDConfiguration] = None):
        self.config = config or AIMDConfiguration()

    @staticmethod
    def _is_valid_number(val: Any) -> bool:
        if val is None:
            return False
        if not isinstance(val, (int, float)) or isinstance(val, bool):
            return False
        if math.isnan(val) or math.isinf(val):
            return False
        return True

    def _extract_health(self, context: AIMDContext) -> Tuple[Optional[float], Optional[str]]:
        """Safely extract and sanitize health score and status from context."""
        score: Optional[float] = None
        status: Optional[str] = None

        if context.health_assessment is not None:
            if self._is_valid_number(context.health_assessment.health_score):
                score = float(context.health_assessment.health_score)
            if context.health_assessment.health_status is not None:
                status = context.health_assessment.health_status.value

        # Fallback to explainability health indicators if direct assessment is missing
        if score is None and context.explainability_result is not None:
            if self._is_valid_number(context.explainability_result.health_score):
                score = float(context.explainability_result.health_score)
        if status is None and context.explainability_result is not None:
            if context.explainability_result.health_status:
                status = context.explainability_result.health_status

        return score, status

    def _has_usable_signals(self, context: AIMDContext) -> bool:
        """Verify whether the context contains at least one meaningful, non-insufficient analytical signal."""
        # Check health assessment
        if context.health_assessment is not None:
            if context.health_assessment.health_status != HealthStatus.INSUFFICIENT_DATA:
                return True

        # Check performance analysis
        if context.performance_analysis is not None:
            if context.performance_analysis.overall_status != PerformanceStatus.INSUFFICIENT_DATA:
                return True

        # Check data drift analysis
        if context.data_drift_analysis is not None:
            if context.data_drift_analysis.drift_detected is not None:
                return True

        # Check concept drift analysis
        if context.concept_drift_analysis is not None:
            if context.concept_drift_analysis.status != ConceptDriftStatus.INSUFFICIENT_DATA:
                return True

        # Check explainability result
        if context.explainability_result is not None:
            if context.explainability_result.has_explanation:
                return True

        return False

    def _check_rollback_safety(self, context: AIMDContext) -> Tuple[bool, Optional[str]]:
        """
        Enforce rollback safety: A rollback is only viable if historical context
        explicitly confirms that an alternate stable model version is available.
        """
        hist = context.historical_maintenance_context
        if not hist or not isinstance(hist, dict):
            return False, "No historical maintenance context provided"

        if not hist.get("rollback_target_available", False):
            return False, "No verified rollback target model available in registry"

        target_version = hist.get("previous_stable_version") or hist.get("target_model_version")
        desc = f"Verified rollback target available ({target_version})" if target_version else "Verified rollback target available"
        return True, desc

    def evaluate(self, context: AIMDContext) -> AIMDRecommendation:
        """
        Evaluate aggregated analytical context and generate a maintenance recommendation.
        """
        score, status = self._extract_health(context)
        supporting_signals: List[str] = []
        evidence_summary: Dict[str, Any] = {}

        # Record health metrics in evidence summary
        if score is not None:
            evidence_summary["health_score"] = score
        if status is not None:
            evidence_summary["health_status"] = status

        # Step 1: Check for insufficient evidence
        if not self._has_usable_signals(context):
            return AIMDRecommendation(
                action=AIMDAction.HUMAN_REVIEW,
                priority=AIMDPriority.MEDIUM,
                rationale="Insufficient analytical and monitoring evidence to determine model health or operational state. Human review of data pipelines and observation logs is required.",
                supporting_signals=["insufficient_data"],
                health_score=score,
                health_status=status or HealthStatus.INSUFFICIENT_DATA.value,
                confidence=AIMDConfidence.INSUFFICIENT,
                requires_human_approval=True,
                evidence_summary={"reason": "insufficient_usable_signals"}
            )

        # Step 2: Signal Extraction & Normalization
        # Performance trend
        perf_degraded = False
        if context.performance_analysis is not None:
            if context.performance_analysis.overall_status == PerformanceStatus.DEGRADED:
                perf_degraded = True
                supporting_signals.append(f"performance_degraded({', '.join(context.performance_analysis.degraded_metrics)})")
                evidence_summary["degraded_metrics"] = context.performance_analysis.degraded_metrics
            elif context.performance_analysis.overall_status == PerformanceStatus.STABLE:
                supporting_signals.append("performance_stable")
            elif context.performance_analysis.overall_status == PerformanceStatus.IMPROVING:
                supporting_signals.append("performance_improving")

        # Concept drift
        concept_drift_detected = False
        if context.concept_drift_analysis is not None:
            if context.concept_drift_analysis.drift_detected is True or context.concept_drift_analysis.status == ConceptDriftStatus.DRIFTED:
                concept_drift_detected = True
                supporting_signals.append(f"concept_drift_detected({', '.join(context.concept_drift_analysis.drifted_metrics)})")
                evidence_summary["concept_drift_metrics"] = context.concept_drift_analysis.drifted_metrics
            elif context.concept_drift_analysis.status == ConceptDriftStatus.NO_DRIFT:
                supporting_signals.append("no_concept_drift")

        # Data drift
        data_drift_detected = False
        drifted_features_count = 0
        if context.data_drift_analysis is not None:
            if context.data_drift_analysis.drift_detected is True or len(context.data_drift_analysis.drifted_features) > 0:
                data_drift_detected = True
                drifted_features_count = len(context.data_drift_analysis.drifted_features)
                supporting_signals.append(f"data_drift_detected({', '.join(context.data_drift_analysis.drifted_features)})")
                evidence_summary["drifted_features"] = context.data_drift_analysis.drifted_features
            elif context.data_drift_analysis.drift_detected is False:
                supporting_signals.append("no_data_drift")

        # Health classification
        is_critical_health = (status == HealthStatus.CRITICAL.value) or (score is not None and score < self.config.critical_health_threshold)
        is_warning_health = (status == HealthStatus.WARNING.value) or (score is not None and self.config.critical_health_threshold <= score < self.config.warning_health_threshold)
        is_healthy = (status == HealthStatus.HEALTHY.value) or (score is not None and score >= self.config.warning_health_threshold)

        if is_critical_health:
            supporting_signals.insert(0, f"health_critical(score={score})")
        elif is_warning_health:
            supporting_signals.insert(0, f"health_warning(score={score})")
        elif is_healthy:
            supporting_signals.insert(0, f"health_healthy(score={score})")

        # Explainability factors inclusion
        if context.explainability_result is not None and context.explainability_result.has_explanation:
            evidence_summary["explainability_primary_factors"] = context.explainability_result.primary_factors
            evidence_summary["explainability_confidence"] = context.explainability_result.confidence
            for factor in context.explainability_result.primary_factors:
                if factor not in supporting_signals:
                    supporting_signals.append(f"factor({factor})")

        # Step 3: Decision Logic Evaluation

        score_str = f"{score:.1f}" if score is not None else "N/A"

        # Rule 1: CRITICAL HEALTH / SEVERE PERFORMANCE COLLAPSE
        if is_critical_health or (perf_degraded and score is not None and score < self.config.critical_health_threshold):
            can_rollback, rollback_reason = self._check_rollback_safety(context)
            if can_rollback:
                action = AIMDAction.ROLLBACK
                priority = AIMDPriority.CRITICAL
                rationale = (
                    f"Model operational health is CRITICAL (score: {score_str}). "
                    f"{rollback_reason}. Immediate rollback to a verified stable model version is recommended "
                    f"to restore production classification reliability, subject to human approval."
                )
            else:
                action = AIMDAction.RETRAIN
                priority = AIMDPriority.CRITICAL
                rationale = (
                    f"Model operational health is CRITICAL (score: {score_str}). "
                    f"Rollback is precluded ({rollback_reason}). Urgent model retraining on recent verified "
                    f"production data is recommended, subject to human approval."
                )

            # Confidence determination
            corroborating_count = sum([is_critical_health, perf_degraded, concept_drift_detected, data_drift_detected])
            confidence = AIMDConfidence.HIGH if corroborating_count >= 2 else AIMDConfidence.MODERATE

            return AIMDRecommendation(
                action=action,
                priority=priority,
                rationale=rationale,
                supporting_signals=supporting_signals,
                health_score=score,
                health_status=status or HealthStatus.CRITICAL.value,
                confidence=confidence,
                requires_human_approval=True,
                evidence_summary=evidence_summary
            )

        # Rule 2: CONCEPT DRIFT DETECTED
        # Concept drift indicates that input-to-target relationship has shifted; model retraining is the primary intervention.
        if concept_drift_detected:
            priority = AIMDPriority.CRITICAL if (is_warning_health or perf_degraded) else AIMDPriority.HIGH
            drifted_metrics_str = ", ".join(context.concept_drift_analysis.drifted_metrics) if context.concept_drift_analysis else "observed metrics"
            rationale = (
                f"Concept drift detected across labeled evaluation windows affecting {drifted_metrics_str}. "
                f"The predictive relationship between input features and spam classification targets has shifted. "
                f"Model retraining with recent ground-truth labeled instances is recommended."
            )
            # High confidence if corroborated by performance degradation or explainability
            has_corroboration = perf_degraded or (context.explainability_result is not None and len(context.explainability_result.primary_factors) > 0)
            confidence = AIMDConfidence.HIGH if has_corroboration else AIMDConfidence.MODERATE

            return AIMDRecommendation(
                action=AIMDAction.RETRAIN,
                priority=priority,
                rationale=rationale,
                supporting_signals=supporting_signals,
                health_score=score,
                health_status=status or (HealthStatus.WARNING.value if is_warning_health else HealthStatus.HEALTHY.value),
                confidence=confidence,
                requires_human_approval=True,
                evidence_summary=evidence_summary
            )

        # Rule 3: PERFORMANCE DEGRADATION WITHOUT DETECTED DRIFT
        # Performance drop without detected data or concept drift indicates uncharacterized root cause.
        # Blindly retraining is not recommended; human investigation is required first.
        if (perf_degraded or is_warning_health) and not data_drift_detected and not concept_drift_detected:
            priority = AIMDPriority.HIGH if perf_degraded else AIMDPriority.MEDIUM
            rationale = (
                "Performance degradation observed without accompanying feature data drift or concept drift. "
                "Because root causes (e.g. data quality anomalies, labeling latency, or external systemic changes) "
                "are uncharacterized, automated retraining is not advisable. Human review and diagnostic inspection "
                "are recommended."
            )
            confidence = AIMDConfidence.MODERATE

            return AIMDRecommendation(
                action=AIMDAction.HUMAN_REVIEW,
                priority=priority,
                rationale=rationale,
                supporting_signals=supporting_signals,
                health_score=score,
                health_status=status or HealthStatus.WARNING.value,
                confidence=confidence,
                requires_human_approval=True,
                evidence_summary=evidence_summary
            )

        # Rule 4: HEALTH WARNING WITH CONCURRENT DATA DRIFT
        if is_warning_health and data_drift_detected:
            rationale = (
                "Model health has degraded to WARNING state concurrent with observed feature data drift. "
                "Feature distribution shift is accompanied by declining composite health scores. "
                "Recommend model retraining on recent operational data."
            )
            return AIMDRecommendation(
                action=AIMDAction.RETRAIN,
                priority=AIMDPriority.HIGH,
                rationale=rationale,
                supporting_signals=supporting_signals,
                health_score=score,
                health_status=status or HealthStatus.WARNING.value,
                confidence=AIMDConfidence.HIGH,
                requires_human_approval=True,
                evidence_summary=evidence_summary
            )

        # Rule 5: DATA DRIFT DETECTED (HEALTHY MODEL WITHOUT PERFORMANCE DEGRADATION)
        # Input features have shifted, but model classification accuracy and health remain acceptable.
        if data_drift_detected and not perf_degraded and not concept_drift_detected and not is_critical_health and not is_warning_health:
            if drifted_features_count >= self.config.data_drift_collection_threshold:
                action = AIMDAction.DATA_COLLECTION
                priority = AIMDPriority.MEDIUM
                rationale = (
                    f"Statistical data drift detected across {drifted_features_count} input features while classification "
                    f"performance remains stable. Recommend collecting and labeling representative production samples "
                    f"from the shifted feature distributions to evaluate future performance robustness."
                )
            else:
                action = AIMDAction.INCREASED_MONITORING
                priority = AIMDPriority.MEDIUM
                rationale = (
                    f"Statistical data drift detected in {drifted_features_count} feature(s) without measurable performance degradation. "
                    f"Recommend increasing monitoring observation frequency to detect any latent classification impact."
                )

            confidence = AIMDConfidence.HIGH if (context.data_drift_analysis and context.data_drift_analysis.features_analyzed >= 2) else AIMDConfidence.MODERATE

            return AIMDRecommendation(
                action=action,
                priority=priority,
                rationale=rationale,
                supporting_signals=supporting_signals,
                health_score=score,
                health_status=status or HealthStatus.HEALTHY.value,
                confidence=confidence,
                requires_human_approval=True,
                evidence_summary=evidence_summary
            )

        # Rule 6: HEALTHY AND STABLE MODEL
        if is_healthy and not perf_degraded and not concept_drift_detected and not data_drift_detected:
            return AIMDRecommendation(
                action=AIMDAction.CONTINUE_MONITORING,
                priority=AIMDPriority.LOW,
                rationale="Model health and performance are within acceptable operational limits. No data drift or concept drift detected. Continue standard monitoring schedule.",
                supporting_signals=supporting_signals,
                health_score=score,
                health_status=status or HealthStatus.HEALTHY.value,
                confidence=AIMDConfidence.HIGH,
                requires_human_approval=True,
                evidence_summary=evidence_summary
            )

        # Default Fallback: Human Review
        return AIMDRecommendation(
            action=AIMDAction.HUMAN_REVIEW,
            priority=AIMDPriority.MEDIUM,
            rationale="Ambiguous or mixed operational monitoring signals observed. Human review is recommended to evaluate appropriate maintenance action.",
            supporting_signals=supporting_signals,
            health_score=score,
            health_status=status,
            confidence=AIMDConfidence.LOW,
            requires_human_approval=True,
            evidence_summary=evidence_summary
        )
