"""Add monitoring observations table

Revision ID: 38dc8f99dc6c
Revises: e4cbbfe86b34
Create Date: 2026-09-07 20:39:58.930203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dc8f99dc6c'
down_revision: Union[str, None] = 'e4cbbfe86b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction_count', sa.Integer(), nullable=False),
    sa.Column('positive_prediction_count', sa.Integer(), nullable=False),
    sa.Column('negative_prediction_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['registered_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_observations_model_id'), 'monitoring_observations', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_observations_model_id'), table_name='monitoring_observations')
    op.drop_table('monitoring_observations')
    # ### end Alembic commands ###
