"""add_decision_logs_table

Revision ID: c30a5d242a96
Revises: 38dc8f99dc6c
Create Date: 2026-09-08 22:01:08.090632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30a5d242a96'
down_revision: Union[str, None] = '38dc8f99dc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('recommended_action', sa.Enum('CONTINUE_MONITORING', 'INCREASED_MONITORING', 'RETRAIN', 'ROLLBACK', 'DATA_COLLECTION', 'HUMAN_REVIEW', name='aimdaction'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='aimdpriority'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('supporting_signals', sa.JSON(), nullable=True),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['registered_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_logs_model_id'), 'decision_logs', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_logs_model_id'), table_name='decision_logs')
    op.drop_table('decision_logs')
    sa.Enum(name='approvalstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='aimdpriority').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='aimdaction').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
