"""Add registered models

Revision ID: e4cbbfe86b34
Revises: b9b363044e54
Create Date: 2026-09-07 19:43:34.515832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cbbfe86b34'
down_revision: Union[str, None] = 'b9b363044e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DEVELOPMENT', 'ACTIVE', 'ARCHIVED', name='modelstatus'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registered_models_name'), 'registered_models', ['name'], unique=False)
    op.create_index(op.f('ix_registered_models_owner_id'), 'registered_models', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registered_models_owner_id'), table_name='registered_models')
    op.drop_index(op.f('ix_registered_models_name'), table_name='registered_models')
    op.drop_table('registered_models')
    # ### end Alembic commands ###
